### ISSUE TITLE
After configuration the progress bar

### ISSUE THREAD

**Issue by tswart** [AuraQ/toastrForMendix#1]
After configuration of the widget the progress bar keeps running and the notification is not shown.
(Mx version: 6.10.3)

**Comment by lindski** [comment]
How do you have the widget configured? Are you able to reproduce this in the widget's test project or do you have your own test project you can share?

**Comment by tswart** [comment]
I just created a test project imported the widget. Created a notification object and frame object (dataview) where I show the widget, configured the widget and entered a single notifcation.
After starting the application the progress bar keeps running....no notification is shown.
Am I missing something?

**Comment by lindski** [comment]
Is there anything in the browser console?

**Comment by tswart** [comment]
No nothing in the browser console.

**Comment by lindski** [comment]
Can you export your test project and upload it here for me to take a look at?

**Comment by tswart** [comment]
[Test.txt](https://github.com/AuraQ/toastrForMendix/files/946884/Test.txt)

Just rename to Test.mpk

**Comment by lindski** [comment]
The widget seems to be clashing with the Notification widget that is also included in the test project. 

If I take the dataview sourced from DS_ShowMessage off the home page then the page (and toastr notification) load fine without any errors in the console. 

If I take the dataview sourced from DS_ShowNotification off the home page then the page (and notification) load fine but there is an error written to the console "mxui.js:5 Error: multipleDefine". I suspect this is related to a jQuery loading conflict.

There is one other minor issue... the notification type is case sensitive so your test record will currently fail as the type is defined as "Success" rather than "success". I can improve the widget's handling of this to treat the value as case insensitive and then validate it against the allowed types (falling back to the default if its invalid) but for now if you can make the type value lower case you can work around this issue.

**Comment by tswart** [comment]
Thanks Lain.

**Comment by lindski** [comment]
V1.1.0 has been created that treats the type attribute as case insensitive
